version: '3'

services: 

  react:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "cp -r /cache/node_modules/. /startup_together/node_modules/
      && chmod 777 /startup_together/node_modules/
      && npm start"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    volumes:
      - ./startup_together:/startup_together
    depends_on:
      - db
    tty: true
    stdin_open: true

  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./rest_api:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres